create table ordered_item
(
    ordered_item_id         int8 generated by default as identity,
    amount_ordered          int8           not null,
    shipping_date           timestamp      not null,
    total_cost_ordered_item numeric(19, 2) not null,
    item_fk                 int8,
    ordered_items_fk        int8           not null,
    primary key (ordered_item_id)
);