create table users
(
    user_id            int8 generated by default as identity,
    city_name          varchar(255) not null,
    zipcode            int4         not null,
    street             varchar(255) not null,
    street_address     varchar(255) not null,
    email              varchar(255) not null,
    home_phonenumber   varchar(255),
    mobile_phonenumber varchar(255),
    firstname          varchar(255) not null,
    lastname           varchar(255) not null,
    password           varchar(255) not null,
    role               varchar(255) not null,
    username           varchar(255) not null,
    primary key (user_id)
);